[workspace]

members = ["salvation", "macros", "tests", "uitest", "test_kit"]
resolver = "2"

[workspace.dependencies]
salvation = { path = "salvation" }
salvation_macros = { path = "macros", version = "0.0.1" }
uitest = { path = "uitest" }
salvation_test_kit = { path = "test_kit" }

accesskit = "0.16.0"
accesskit_winit = "0.22.0"
anyhow = { version = "1.0.80", features = ["backtrace"] }
arboard = "3.2.1"
bitflags = "2.4.0"
bytemuck = "1.13.1"
clap = { version = "4.5.16", features = ["derive"] }
cosmic-text = "0.11.2"
ctor = "0.2.9"
derivative = "2.2.0"
derive_more = "0.99.17"
env_logger = "0.10.0"
fs-err = "2.11.0"
image = "0.25.2"
itertools = "0.13.0"
lightningcss = { version = "1.0.0-alpha.49", features = ["serde"] }
line-straddler = "0.2.1"
log = "0.4.20"
once_cell = "1.18.0"
ordered-float = "4.6.0"
png = "0.17.10"
priority-queue = "1.3.2"
quote = "1.0.33"
range-ext = "0.3.0"
resvg = { version = "0.36.0", default-features = false }
scoped-tls = "1.0.1"
serde = { version = "1.0.188", features = ["derive"] }
serde-value = "0.7.0"
softbuffer = "0.4.1"
strict-num = "0.1.1"
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.25.2"
syn = { version = "2.0.58", features = ["full"] }
thiserror = "1.0.49"
tiny-skia = "0.11.1"
typed-builder = "0.16.0"
unicode-segmentation = "1.10.1"
usvg = { version = "0.36.0", default-features = false }
winit = "0.30.7"
x11rb = { version = "0.13.0", features = ["res"] }
xcap = "0.6.0"
