[package]
name = "salvation"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "0.11.1"
png = "0.17.10"
#cosmic-text = "0.9.0"
cosmic-text = { path = "../cosmic-text" }
winit = "0.29.1-beta"
softbuffer = "0.3.0"
bytemuck = "1.13.1"
downcast-rs = "1.2.0"
scoped-tls = "1.0.1"
derive_more = "0.99.17"
bitflags = "2.4.0"
once_cell = "1.18.0"
anyhow = { version = "1.0.75", features = ["backtrace"] }
