name = "cicd"
version = "0.1.0"

[dependencies]
cicd = "=0.9.0-pre.1"
distrib = "=0.9.0-pre.1"
fs = "=0.9.0-pre.1"
http = "=0.9.0-pre.1"
log = "=0.9.0-pre.1"
net = "=0.9.0-pre.1"
process = "=0.9.0-pre.1"
std = "=0.9.0-pre.1"
work = "=0.9.0-pre.1"

[entrypoints]
main = "cicd::main"
