on: [push, pull_request]

name: Continuous integration

jobs:
  build-deps:
    name: Install build dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libxcb1-dev libxrandr-dev \
            libdbus-1-dev libpipewire-0.3-dev libwayland-dev libegl-dev \
            libgbm-dev
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt

  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    needs: build-deps
    steps:
      - run: cargo test

  ui-tests:
    name: UI tests
    runs-on: ubuntu-24.04
    needs: build-deps
    steps:
      - name: Build tests
        run: |
          cargo build --package widgem_tests --release --locked
          mkdir -p target/bin
          cp target/release/widgem_tests target/bin/
      - name: "Build docker image"
        uses: docker/build-push-action@v6
        with:
          context: target/bin
          tags: widgem_tests
          file: tests/tests.Dockerfile
          load: true
      - name: Run UI tests
        run: |
          docker run --name widgem_tests \
            --mount "type=bind,source=$PWD,target=/app" \
            widgem_tests widgem_tests test
      - name: Upload test snapshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test_snapshots
          path: tests/snapshots

  fmt:
    name: Rustfmt
    needs: build-deps
    runs-on: ubuntu-24.04
    steps:
      - uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Clippy
    needs: build-deps
    runs-on: ubuntu-24.04
    steps:
      - run: cargo clippy --all-targets --all-features -- --deny warnings
