on: [push, pull_request]

name: Integration test

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build --cache-to type=gha,mode=max --cache-from type=gha -t salvation_tests -f tests/Dockerfile .

    - name: Run Docker container
      run: docker run -d --name salvation_tests --mount "type=bind,source=$PWD,target=/salvation" salvation_tests
    - name: Run tests
      run: |
        for i in {1..20}; do
          sleep 0.3
          echo Testing container status
          docker exec salvation_tests xdotool click 1 || true
          if docker exec salvation_tests xdotool getactivewindow; then
            echo Container is ready
            break
          fi
        done
        docker exec salvation_tests salvation_tests -- --check
